version: '3'
services:
  backend:
    image: 'maven:3-jdk-8-alpine'
    volumes:
     - ./produto-back:/app/
    command: mvn spring-boot:run
    working_dir: /app
    ports:
     - 8080:8080

  frontend:
    image: 'node:lts-alpine'
    volumes:
     - ./projetos-react/front-end/produto-app:/app/
    command: sh -c "npm i && npm start"
    working_dir: /app
    ports:
     - 3000:3000
