version: '3'
services:
  backend:
    image: jozimar/crud_produtos_back:1.0.0
    ports:
      - 8080:8080
    restart: unless-stopped

  frontend:
    image: jozimar/crud_produtos:1.0.0
    ports:
      - 3000:80
    restart: unless-stopped
